version: "3.4"
services:
    mysql:
        restart: always
        image: mysql:5.7
        container_name: mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: project
            MYSQL_USER: project
            MYSQL_PASSWORD: project
        ports:
            - 3306:3306
        volumes:
            - mysql:/var/lib/mysql
    mongodb:
        restart: always
        image: mongo
        container_name: mongodb
        ports:
            - 27017:27017
            - 27018:27017
        volumes:
            - mongodb:/data/db
    keyrock:
        restart: always
        image: fiware/idm:7.6.0
        container_name: keyrock
        depends_on:
            - mysql
        ports:
            - 3005:3005
            - 443:443
        environment:
            DEBUG: idm:*
            IDM_DB_HOST: mysql
            IDM_HOST: http://localhost:3005
            IDM_PORT: 3005
            IDM_DB_PASS: root
            IDM_DB_USER: root
            IDM_ADMIN_USER: admin
            IDM_ADMIN_EMAIL: admin@tuc.gr
            IDM_ADMIN_PASS: admin
    app:
        restart: always
        image: app
        container_name: cloud-app
        depends_on:
            - mysql
            - mongodb
            - keyrock
        build:
            context: .
            dockerfile: ./Dockerfile
        environment:
            DB_HOST: mysql
            DB_PORT: 3306
            DB_USER: project
            DB_PASS: project
            DB_NAME: project
            DB_URL: mongodb://mongodb:27017/app
            KEYROCK_HOST: http://keyrock:3005
            KEYROCK_ID: b58858ff-3107-41c2-a93d-d0e3b0794854
            KEYROCK_SECRET: 4b57aebb-b4b5-47e3-9f77-0f174f1033cb
            KEYROCK_ADMIN: admin@tuc.gr
            KEYROCK_PASS: admin
        ports:
            - 80:80
        volumes:
            - "./:/usr/src/app"
volumes:
    mysql: ~
    mongodb: ~
    app: ~
