version: "3.4"

services:
    mysql:
        restart: always
        image: mysql:5.7
        container_name: mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: project
            MYSQL_USER: project
            MYSQL_PASSWORD: project
        ports:
            - 3306:3306
        volumes:
            - mysql:/var/lib/mysql
    mongodb:
        restart: always
        image: mongo:6
        container_name: mongodb
        ports:
            - 27017:27017
            - 27018:27017
        volumes:
            - mongodb:/data/db
    app:
        depends_on:
            - mysql
            - mongodb
        restart: always
        image: app
        container_name: cloud-app
        build:
            context: .
            dockerfile: ./Dockerfile
        environment:
            DB_HOST: mysql
            DB_PORT: 3306
            DB_USER: project
            DB_PASS: project
            DB_NAME: project
            DB_URL: mongodb://mongodb:27017/app
        ports:
            - 80:80
        volumes:
            - "./:/usr/src/app"
    keyrock:
        depends_on:
            - mysql
        image: fiware/idm:7.6.0
        container_name: fiware-keyrock
        ports:
            - 3005:3005
            - 443:443
        environment:
            - DEBUG=idm:*
            - IDM_DB_HOST=mysql
            - IDM_HOST=http://localhost:3005
            - IDM_PORT=3005
            - IDM_DB_PASS=root
            - IDM_DB_USER=root
            - IDM_ADMIN_USER=admin
            - IDM_ADMIN_EMAIL=admin@tuc.gr
            - IDM_ADMIN_PASS=admin

volumes:
    mysql: ~
    mongodb: ~
    app: ~
