version: "3.4"

services:
    mysql:
        restart: always
        image: mysql:8
        container_name: mysql
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: project
            MYSQL_USER: project
            MYSQL_PASSWORD: project
        ports:
            - 3306:3306
        volumes:
            - mysql:/var/lib/mysql
    mongodb:
        restart: always
        image: mongo:6
        container_name: mongodb
        ports:
            - 27017:27017
            - 27018:27017
        volumes:
            - mongodb:/data/db
    app:
        depends_on:
            - mysql
            - mongodb
        restart: always
        image: app
        container_name: project-app
        build:
            context: .
            dockerfile: ./Dockerfile
        environment:
            DB_HOST: mysql
            DB_PORT: 3306
            DB_USER: project
            DB_PASS: project
            DB_NAME: project
            DB_URL: mongodb://mongodb:27017/app
        ports:
            - 80:80
        volumes:
            - "./:/usr/src/app"

volumes:
    mysql: ~
    mongodb: ~
    app: ~
